############# English navigation ##############

# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Preguntas Frecuentes"
url = "preguntas-frecuentes/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

# [[main]]
# name = "Pages"
# url = "#"
# weight = 3
# hasChildren = true

#   [[main]]
#   parent = "Pages"
#   name = "Tags"
#   url = "tags/"
#   weight = 1

#   [[main]]
#   parent = "Pages"
#   name = "Categories"
#   url = "categories/"
#   weight = 2

# footer menu
[[footer]]
name = "Inicio"
url = "/"
weight = 1

[[footer]]
name = "Preguntas Frecuentes"
url = "preguntas-frecuentes/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3

[[footer]]
name = "Políticas de Privacidad"
url = "privacy-policy/"
weight = 4
