#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "150x"
# logo text will only show when logo is missing.
logo_text = "AyunoIntermitente.Blog"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "Ayuno Intermitente Blog"
author = "AyunoIntermitente"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
# address = "9567 Turner Trace Apt. BC C3G8A4"
# mobile = "+211234565523"
# email = "info@email.com"
# contact form action
# contact_form_action = "#" # contact form works with https://formspree.io
# search
search = true

# featured post title
featured_post_title = "Artículos Destacados"
recent_post_title = "Artículos Recientes"
mainSections = ["blog"]
# about widget content
about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
# footer content
footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
# copyright
copyright = "© 2021 Copyright Ayuno Intermitente.Blog"
#copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""


# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "**¡** Bienvenido **!**"
title_small = "a Ayuno Intermitente.Blog"
image = "images/banner.jpg"
background_image = "/images/banner-bg-shape.svg"
content = "El Ayuno Intermitente no es una dieta, es un patrón alimentario en el cual se tiene una ventana de tiempo donde se dejan de ingerir alimentos seguida de un periodo donde consumirás las calorías diarias requeridas. En pocas palabras, el Ayuno Intermitente es un estilo de vida."
button_label = "Comienza Aquí"
button_link = "blog/como-comenzar-el-ayuno-intermitente-2/"

# Advertise
[advertisement]
image = "images/promotion.png"
link = "https://ayunointermitente.blog/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/ayunointermitente.blog"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/ayuno_blog"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/ayunointermitente.blog/"

# [[social]]
# title = "github"
# icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#"

# [[social]]
# title = "linkedin"
# icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
# link = "#"
